apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-app-access

spec:
  podSelector:
    matchLabels:
      app: devops

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
